name: mfe-mono

networks:
  mfe-mono:
    driver: bridge

services:
  api-server:
    build:
      dockerfile: servers/api-server/Dockerfile
    ports:
      - '${API_SERVER_PORT}:${API_SERVER_PORT}'
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mfe-mono
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://localhost:${API_SERVER_PORT}/api']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s
  module-calculator:
    build:
      dockerfile: apps/modules/calculator/Dockerfile
    environment:
      - NX_PUBLIC_API_SERVER_ADDRESS=http://api-server
    ports:
      - '81:80'
    restart: unless-stopped
    networks:
      - mfe-mono
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://module-calculator']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s
  module-todolist:
    build:
      dockerfile: apps/modules/todolist/Dockerfile
    environment:
      - NX_PUBLIC_API_SERVER_ADDRESS=http://api-server
    ports:
      - '82:80'
    restart: unless-stopped
    networks:
      - mfe-mono
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://module-todolist']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s
  module-crud:
    build:
      dockerfile: apps/modules/crud/Dockerfile
    environment:
      - NX_PUBLIC_API_SERVER_ADDRESS=http://api-server
    ports:
      - '83:80'
    restart: unless-stopped
    networks:
      - mfe-mono
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://module-crud']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s
  module-lodash-v3:
    build:
      dockerfile: apps/modules/lodash-v3/Dockerfile
    environment:
      - NX_PUBLIC_API_SERVER_ADDRESS=http://api-server
    ports:
      - '84:80'
    restart: unless-stopped
    networks:
      - mfe-mono
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://module-lodash-v3']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s
  module-lodash-v4:
    build:
      dockerfile: apps/modules/lodash-v4/Dockerfile
    environment:
      - NX_PUBLIC_API_SERVER_ADDRESS=http://api-server
    ports:
      - '85:80'
    restart: unless-stopped
    networks:
      - mfe-mono
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://module-lodash-v4']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s
  module-clock-v4:
    build:
      dockerfile: apps/modules/clock-v4/Dockerfile
    environment:
      - NX_PUBLIC_API_SERVER_ADDRESS=http://api-server
    ports:
      - '86:80'
    restart: unless-stopped
    networks:
      - mfe-mono
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://module-clock-v4']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s
  module-clock-v5:
    build:
      dockerfile: apps/modules/clock-v5/Dockerfile
    environment:
      - NX_PUBLIC_API_SERVER_ADDRESS=http://api-server
    ports:
      - '87:80'
    restart: unless-stopped
    networks:
      - mfe-mono
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://module-clock-v5']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s
  shell:
    depends_on:
      api-server:
        condition: service_healthy
      module-calculator:
        condition: service_healthy
      module-todolist:
        condition: service_healthy
      module-crud:
        condition: service_healthy
      module-lodash-v3:
        condition: service_healthy
      module-lodash-v4:
        condition: service_healthy
      module-clock-v4:
        condition: service_healthy
      module-clock-v5:
        condition: service_healthy
    build:
      dockerfile: apps/shell/Dockerfile
    environment:
      - NX_PUBLIC_API_SERVER_ADDRESS=http://api-server
      - REMOTE_CALCULATOR=http://module-calculator
      - REMOTE_TODOLIST=http://module-todolist
      - REMOTE_CRUD=http://module-crud
      - REMOTE_LODASH_V3=http://module-lodash-v3
      - REMOTE_LODASH_V4=http://module-lodash-v4
      - REMOTE_CLOCK_V4=http://module-clock-v4
      - REMOTE_CLOCK_V5=http://module-clock-v5
    ports:
      - '80:80'
    restart: unless-stopped
    networks:
      - mfe-mono
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://shell']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s
